// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseAudioInfo } from './BaseAudioInfo.js';
import type { BaseFileInfo } from './BaseFileInfo.js';
import type { BaseImageInfo } from './BaseImageInfo.js';
import type { BaseVideoInfo } from './BaseVideoInfo.js';

/**
 * Types of metadata for an attachment.
 */
export type AttachmentInfo =
	| { kind: 'image'; info: BaseImageInfo }
	| { kind: 'video'; info: BaseVideoInfo }
	| { kind: 'audio'; info: BaseAudioInfo }
	| { kind: 'file'; info: BaseFileInfo }
	| { kind: 'voice'; info: BaseAudioInfo };
