// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about an audio clip.
 */
export type AudioInfo = {
	/**
	 * The duration of the audio in milliseconds.
	 */
	duration?: number | null;
	/**
	 * The mimetype of the audio, e.g. "audio/aac".
	 */
	mimetype: string | null;
	/**
	 * The size of the audio clip in bytes.
	 */
	size: number | null;
};
