// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioInfo } from './AudioInfo.js';
import type { EncryptedFile } from './EncryptedFile.js';
import type { UnstableAudioDetailsContentBlock } from './UnstableAudioDetailsContentBlock.js';
import type { UnstableVoiceContentBlock } from './UnstableVoiceContentBlock.js';

/**
 * The payload for an audio message.
 */
export type AudioMessageEventContent = {
	/**
	 * The textual representation of this message.
	 *
	 * If the `filename` field is not set or has the same value, this is the filename of the
	 * uploaded file. Otherwise, this should be interpreted as a user-written media caption.
	 */
	body: string;
	/**
	 * The original filename of the uploaded file as deserialized from the event.
	 *
	 * It is recommended to use the `filename` method to get the filename which automatically
	 * falls back to the `body` field when the `filename` field is not set.
	 */
	filename: string | null;
	/**
	 * Metadata for the audio clip referred to in `source`.
	 */
	info: AudioInfo | null;
	/**
	 * Extensible event fallback data for audio messages, from the
	 * [first version of MSC3245][msc].
	 *
	 * [msc]: https://github.com/matrix-org/matrix-spec-proposals/blob/83f6c5b469c1d78f714e335dcaa25354b255ffa5/proposals/3245-voice-messages.md
	 */
	'org.matrix.msc1767.audio': UnstableAudioDetailsContentBlock | null;
	/**
	 * Extensible event fallback data for voice messages, from the
	 * [first version of MSC3245][msc].
	 *
	 * [msc]: https://github.com/matrix-org/matrix-spec-proposals/blob/83f6c5b469c1d78f714e335dcaa25354b255ffa5/proposals/3245-voice-messages.md
	 */
	'org.matrix.msc3245.voice': UnstableVoiceContentBlock | null;
} & ({ url: string } | { file: EncryptedFile });
