// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base metadata about an audio clip.
 */
export type BaseAudioInfo = {
	/**
	 * The duration of the audio clip.
	 */
	duration: { secs: number; nanos: number } | null;
	/**
	 * The file size of the audio clip in bytes.
	 */
	size: number | null;
	/**
	 * The waveform of the audio clip.
	 *
	 * Must only include values between 0 and 1.
	 */
	waveform: Array<number> | null;
};
