// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base metadata about a file.
 */
export type BaseFileInfo = {
	/**
	 * The size of the file in bytes.
	 */
	size: number | null;
};
