// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base metadata about an image.
 */
export type BaseImageInfo = {
	/**
	 * The height of the image in pixels.
	 */
	height: number | null;
	/**
	 * The width of the image in pixels.
	 */
	width: number | null;
	/**
	 * The file size of the image in bytes.
	 */
	size: number | null;
	/**
	 * The [BlurHash](https://blurha.sh/) for this image.
	 */
	blurhash: string | null;
	/**
	 * Whether this image is animated.
	 */
	is_animated: boolean | null;
};
