// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base metadata about a video.
 */
export type BaseVideoInfo = {
	/**
	 * The duration of the video.
	 */
	duration: { secs: number; nanos: number } | null;
	/**
	 * The height of the video in pixels.
	 */
	height: number | null;
	/**
	 * The width of the video in pixels.
	 */
	width: number | null;
	/**
	 * The file size of the video in bytes.
	 */
	size: number | null;
	/**
	 * The [BlurHash](https://blurha.sh/) for this video.
	 */
	blurhash: string | null;
};
