// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload to edit current user's information.
 * Only the Some(...) fields are updated, None are ignored.
 */
export type EditUserInformationPayload = {
	newDisplayName: string | null;
	newAvatarUri: string | null;
	newDeviceName: string | null;
};
