// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload for an emote message.
 */
export type EmoteMessageEventContent = {
	/**
	 * The emote action to perform.
	 */
	body: string;
	/**
	 * The formatted body. TODO: support formatted bodies
	 */
	// formatted: FormattedBody;
};
