// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonWebKey } from './JsonWebKey.js';

/**
 * A file sent to a room with end-to-end encryption enabled.
 *
 * To create an instance of this type, first create a `EncryptedFileInit` and convert it via
 * `EncryptedFile::from` / `.into()`.
 */
export type EncryptedFile = {
	/**
	 * The URL to the file.
	 */
	url: string;
	/**
	 * A [JSON Web Key](https://tools.ietf.org/html/rfc7517#appendix-A.3) object.
	 */
	key: JsonWebKey;
	/**
	 * The 128-bit unique counter block used by AES-CTR, encoded as unpadded base64.
	 */
	iv: string;
	/**
	 * A map from an algorithm name to a hash of the ciphertext, encoded as unpadded base64.
	 *
	 * Clients should support the SHA-256 hash, which uses the key sha256.
	 */
	hashes: Record<string, string>;
	/**
	 * Version of the encrypted attachments protocol.
	 *
	 * Must be `v2`.
	 */
	v: string;
};
