// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThumbnailInfo } from './ThumbnailInfo.js';

/**
 * Metadata about a file.
 */
export type FileInfo = {
	/**
	 * The mimetype of the file, e.g. "application/msword".
	 */
	mimetype: string | null;
	/**
	 * The size of the file in bytes.
	 */
	size: number | null;
	/**
	 * Metadata about the image referred to in `thumbnail_source`.
	 */
	thumbnail_info: ThumbnailInfo | null;
};
