// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageFormat } from './MessageFormat.js';

/**
 * Common message event content fields for message types that have separate plain-text and
 * formatted representations.
 */
export type FormattedBody = {
	/**
	 * The format used in the `formatted_body`.
	 */
	format: MessageFormat;
	/**
	 * The formatted version of the `body`.
	 */
	formatted_body: string;
};
