// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceGuessedType } from './DeviceGuessedType.js';
import type { MilliSecondsSinceUnixEpoch } from './MilliSecondsSinceUnixEpoch.js';

export type FrontendDevice = {
	deviceId: string;
	isVerified: boolean;
	isVerifiedWithCrossSigning: boolean;
	displayName: string | null;
	lastSeenTs: MilliSecondsSinceUnixEpoch | null;
	guessedType: DeviceGuessedType;
	isCurrentDevice: boolean;
};
