// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrontendRoomMember = {
	name: string;
	maxPowerLevel: { userPowerLevel: boolean | number };
	displayNameAmbiguous: boolean;
	isIgnored: boolean;
};
