// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { FormattedBody } from './FormattedBody.js';

/**
 * Custom TextMessage struct that adds a Vec of matched URLs
 * The payload for a text message.
 */
export type FrontendTextMessage = {
	/**
	 * The body of the message.
	 */
	body: string;
	/**
	 * Custom utility field since we don't support full url_previews right now
	 */
	matched_urls: string[] | null;
} & Partial<FormattedBody>;
