// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThumbnailMediaSource } from '../matrix-requests/media.js';
import type { ThumbnailInfo } from './ThumbnailInfo.js';

/**
 * Metadata about an image.
 */
export type ImageInfo = {
	/**
	 * The height of the image in pixels.
	 */
	h: number | null;
	/**
	 * The width of the image in pixels.
	 */
	w: number | null;
	/**
	 * The MIME type of the image, e.g. "image/png."
	 */
	mimetype: string | null;
	/**
	 * The file size of the image in bytes.
	 */
	size: number | null;
	/**
	 * Metadata about the image referred to in `thumbnail_source`.
	 */
	thumbnail_info: ThumbnailInfo | null;
	/**
	 * The [BlurHash](https://blurha.sh) for this image.
	 *
	 * This uses the unstable prefix in
	 * [MSC2448](https://github.com/matrix-org/matrix-spec-proposals/pull/2448).
	 */
	'xyz.amorgan.blurhash': string | null;
	/**
	 * The [ThumbHash](https://evanw.github.io/thumbhash/) for this image.
	 *
	 * This uses the unstable prefix in
	 * [MSC2448](https://github.com/matrix-org/matrix-spec-proposals/pull/2448).
	 */
	'xyz.amorgan.thumbhash': string | null;
	/**
	 * Whether the image is animated.
	 *
	 * This uses the unstable prefix in [MSC4230].
	 *
	 * [MSC4230]: https://github.com/matrix-org/matrix-spec-proposals/pull/4230
	 */
	'org.matrix.msc4230.is_animated': boolean | null;
} & ThumbnailMediaSource;
