// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilliSecondsSinceUnixEpoch } from './MilliSecondsSinceUnixEpoch.js';

/**
 * Representation of a bookmark as it is stored
 * in the index. + the serialize trait
 */
export type IndexedBookmark = {
	/**
	 * Event id of the current "version" of the bookmarked
	 * message (latest event of the `m.replace` relation chain)
	 */
	eventId: string;
	/**
	 * "Root" event id of the bookmarked message (first event of
	 * the `m.replace` relation chain)
	 */
	originalEventId: string;
	/**
	 * Event id of the `m.bookmark` event that points to the
	 * bookmarked event and triggered its indexation.
	 */
	pointerEventId: string;
	/**
	 * Body of the bookmarked message. Maybe an empty string if
	 * the event does not have a string representation.
	 */
	body: string;
	/**
	 * When the bookmarked event has been sent
	 */
	originalServerTs: MilliSecondsSinceUnixEpoch;
	/**
	 * Sender of the bookmarked event
	 */
	sender: string;
	/**
	 * Room in which the bookmarked event lives
	 */
	roomId: string;
	/**
	 * Search score
	 */
	score: number;
};
