// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the event a [rich reply] is replying to.
 *
 * [rich reply]: https://spec.matrix.org/latest/client-server-api/#rich-replies
 */
export type InReplyTo = {
	/**
	 * The event being replied to.
	 */
	event_id: string;
};
