// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about the user who invited us to a room.
 */
export type InviterInfo = { userId: string; displayName: string | null; avatar: string | null };
