// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteState } from './InviteState.js';
import type { InviterInfo } from './InviterInfo.js';
import type { MilliSecondsSinceUnixEpoch } from './MilliSecondsSinceUnixEpoch.js';
import type { RoomDisplayName } from './RoomDisplayName.js';

export type InvitedRoomInfo = {
	/**
	 * The matrix ID of this room.
	 */
	roomId: string;
	/**
	 * The displayable name of this room, if known.
	 */
	roomName: RoomDisplayName;
	/**
	 * The canonical alias for this room, if any.
	 */
	canonicalAlias: string | null;
	/**
	 * The alternative aliases for this room, if any.
	 */
	altAliases: Array<string>;
	/**
	 * The avatar for this room: either an array of bytes holding the avatar image
	 * or a string holding the first Unicode character of the room name.
	 */
	roomAvatar: string | null;
	/**
	 * Info about the user who invited us to this room, if available.
	 */
	inviterInfo: InviterInfo | null;
	/**
	 * The timestamp and Html text content of the latest message in this room.
	 */
	latest: [MilliSecondsSinceUnixEpoch, string] | null;
	/**
	 * The state of this how this invite is being handled by the client backend
	 * and what should be shown in the UI.
	 */
	inviteState: InviteState;
	/**
	 * Whether this is an invite to a direct room.
	 */
	isDirect: boolean;
};
