// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestrictedSummary } from './RestrictedSummary.js';

/**
 * The rule used for users wishing to join a room.
 *
 * In contrast to the regular [`JoinRule`], this enum holds only simplified conditions for joining
 * restricted rooms.
 *
 * This type can hold an arbitrary join rule. To check for values that are not available as a
 * documented variant here, get its kind with `.kind()` or use its string representation, obtained
 * through `.as_str()`.
 *
 * Because this type contains a few neighbouring fields instead of a whole object, and it is not
 * possible to know which fields to parse for unknown variants, this type will fail to serialize if
 * it doesn't match one of the documented variants. It is only possible to construct an
 * undocumented variant by deserializing it, so do not re-serialize this type.
 */
export type JoinRuleSummary =
	| { join_rule: 'invite' }
	| { join_rule: 'knock' }
	| { join_rule: 'private' }
	| ({ join_rule: 'restricted' } & RestrictedSummary)
	| ({ join_rule: 'knock_restricted' } & RestrictedSummary)
	| { join_rule: 'public' };
