// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilliSecondsSinceUnixEpoch } from './MilliSecondsSinceUnixEpoch.js';
import type { RoomDisplayName } from './RoomDisplayName.js';
import type { RoomHero } from './RoomHero.js';
import type { TagInfo } from './TagInfo.js';
import type { TagName } from './TagName.js';

/**
 * UI-related info about a joined room.
 *
 * This includes info needed display a preview of that room in the RoomsList
 * and to filter the list of rooms based on the current search filter.
 */
export type JoinedRoomInfo = {
	/**
	 * The matrix ID of this room.
	 */
	roomId: string;
	/**
	 * The displayable name of this room, if known.
	 */
	roomName: RoomDisplayName;
	/**
	 * The number of unread messages in this room.
	 */
	numUnreadMessages: number;
	/**
	 * The number of unread mentions in this room.
	 */
	numUnreadMentions: number;
	/**
	 * The canonical alias for this room, if any.
	 */
	canonicalAlias: string | null;
	/**
	 * The alternative aliases for this room, if any.
	 */
	altAliases: Array<string>;
	/**
	 * The tags associated with this room, if any.
	 * This includes things like is_favourite, is_low_priority,
	 * whether the room is a server notice room, etc.
	 */
	tags: { [key in TagName]?: TagInfo };
	/**
	 * The topic of the current room
	 */
	topic: string | null;
	/**
	 * The timestamp and Html text content of the latest message in this room.
	 */
	latest: [MilliSecondsSinceUnixEpoch, string] | null;
	/**
	 * The avatar for this room
	 */
	avatar: string | null;
	/**
	 * Whether this room has been paginated at least once.
	 * We pre-paginate visible rooms at least once in order to
	 * be able to display the latest message in the room preview,
	 * and to have something to immediately show when a user first opens a room.
	 */
	hasBeenPaginated: boolean;
	/**
	 * Whether this room is currently selected in the UI.
	 */
	isSelected: boolean;
	/**
	 * Whether this a DM room or not.
	 */
	isDirect: boolean;
	/**
	 * UserId of the user if the room is direct
	 */
	directUserId: string | null;
	/**
	 * Whether this room is tombstoned (shut down and replaced with a successor room).
	 */
	isTombstoned: boolean;
	/**
	 * Room "heroes", ~ main users of this room
	 */
	heroes: Array<RoomHero>;
};
