// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A [JSON Web Key](https://tools.ietf.org/html/rfc7517#appendix-A.3) object.
 *
 * To create an instance of this type, first create a `JsonWebKeyInit` and convert it via
 * `JsonWebKey::from` / `.into()`.
 */
export type JsonWebKey = {
	/**
	 * Key type.
	 *
	 * Must be `oct`.
	 */
	kty: string;
	/**
	 * Key operations.
	 *
	 * Must at least contain `encrypt` and `decrypt`.
	 */
	key_ops: Array<string>;
	/**
	 * Algorithm.
	 *
	 * Must be `A256CTR`.
	 */
	alg: string;
	/**
	 * The key, encoded as url-safe unpadded base64.
	 */
	k: string;
	/**
	 * Extractable.
	 *
	 * Must be `true`. This is a
	 * [W3C extension](https://w3c.github.io/webcrypto/#iana-section-jwk).
	 */
	ext: boolean;
};
