// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload for a location message.
 */
export type LocationMessageEventContent = {
	/**
	 * A description of the location e.g. "Big Ben, London, UK", or some kind of content
	 * description for accessibility, e.g. "location attachment".
	 */
	body: string;
	/**
	 * A geo URI representing the location.
	 */
	geo_uri: string;
	/**
	 * Extensible-event timestamp this message refers to.
	 */
	ts: number | null;
};
