// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wether the user has logged in, or is in another state.
 */
export type LoginState = 'initiating' | 'restored' | 'awaitingForHomeserver' | 'loggedIn';
