// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineItem } from './TimelineItem.js';

/**
 * High-level struct that wraps all information about a bookmark
 * for frontend usage
 */
export type MatrixBookmarkItem = {
	/**
	 * The bookmarked event that has been fetched and mapped to a frontend
	 * timeline item.
	 * These are only MsgLike events
	 */
	item: Extract<TimelineItem, { kind: 'msgLike' }>;
	/**
	 * The room_id where this event is in
	 */
	roomId: string;
	/**
	 * The room_display_name of the room this event is in
	 */
	roomName: string | null;
	/**
	 * The avatar of the room this event is in
	 */
	roomAvatar: string | null;
	/**
	 * The avatar_uri of this bookmark's sender
	 */
	senderAvatar: string | null;
};
