// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's account credentials to create a new Matrix session
 */
export type MatrixLoginPayload = {
	username: string;
	password: string;
	homeserverUrl: string;
	clientName: string;
};
