// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomPreview } from './RoomPreview.js';
import type { UserProfile } from './UserProfile.js';

export type MatrixUriPillInfo =
	| { kind: 'room'; payload: [RoomPreview, Array<string>] }
	| { kind: 'user'; payload: UserProfile };
