// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MatrixUriIntent =
	| { kind: 'room'; payload: [string, Array<string>] }
	| { kind: 'user'; payload: string };
