// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedFile } from './EncryptedFile.js';

/**
 * The source of a media file.
 */
export type MediaSource = { url: string } | { file: EncryptedFile };
