// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes whether the event mentions other users or the room.
 */
export type Mentions = {
	/**
	 * The list of mentioned users.
	 *
	 * Defaults to an empty `BTreeSet`.
	 */
	user_ids?: Array<string>;
	/**
	 * Whether the whole room is mentioned.
	 *
	 * Defaults to `false`.
	 */
	room?: boolean;
};
