// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The format for the formatted representation of a message body.
 *<!-- Keep this comment so the content is always included as a new paragraph -->
This type can hold an arbitrary string. To build this with a custom value, convert it from a
string with `::from()` / `.into()`. To check for values that are not available as a
documented variant here, use its string representation, obtained through
[`.as_str()`](Self::as_str()).

 */
export type MessageFormat = 'org.matrix.custom.html';
