// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timestamp represented as the number of milliseconds since the unix epoch.
 */
export type MilliSecondsSinceUnixEpoch = number;
