// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlainMediaSource } from '../matrix-requests/media.js';
import type { AudioMessageEventContent } from './AudioMessageEventContent.js';
import type { EmoteMessageEventContent } from './EmoteMessageEventContent.js';
import type { FileMessageEventContent } from './FileMessageEventContent.js';
import type { ImageInfo } from './ImageInfo.js';
import type { ImageMessageEventContent } from './ImageMessageEventContent.js';
import type { LocationMessageEventContent } from './LocationMessageEventContent.js';
import type { NoticeMessageEventContent } from './NoticeMessageEventContent.js';
import type { ReactionsByKeyBySender } from './ReactionsByKeyBySender.js';
import type { ServerNoticeMessageEventContent } from './ServerNoticeMessageEventContent.js';
import type { TextMessageEventContent } from './TextMessageEventContent.js';
import type { ThreadSummary } from './ThreadSummary.js';
import type { VideoMessageEventContent } from './VideoMessageEventContent.js';

/**
 * A special kind of [`super::TimelineItemContent`] that groups together
 * different room message types with their respective reactions and thread
 * information.
 */
export type MsgLikeContent = {
	/**
	 * Map of user reactions to this message
	 */
	reactions: ReactionsByKeyBySender;
	/**
	 * Event ID of the thread root, if this is a threaded message.
	 */
	threadRoot: string | null;
	/**
	 * The mapped thread summary containing the latest item in this thread + additionnal infos.
	 */
	threadSummary: ThreadSummary | null;
	/**
	 * The event's id this message is replying to, if any.
	 */
	inReplyToId: string | null;
	/**
	 * Wether the event has been edited at least once
	 */
	edited: boolean;
	/**
	 * Sender display name (could be none if not resolved yet)
	 */
	sender: string | null;
	/**
	 * Sender id of the event
	 */
	senderId: string;
} & (
	| { kind: 'audio'; body: AudioMessageEventContent }
	| { kind: 'emote'; body: EmoteMessageEventContent }
	| { kind: 'file'; body: FileMessageEventContent }
	| { kind: 'image'; body: ImageMessageEventContent }
	| { kind: 'location'; body: LocationMessageEventContent }
	| { kind: 'notice'; body: NoticeMessageEventContent }
	| { kind: 'serverNotice'; body: ServerNoticeMessageEventContent }
	| { kind: 'text'; body: TextMessageEventContent }
	| { kind: 'video'; body: VideoMessageEventContent }
	| { kind: 'sticker'; body: StickerEventContent }
	| { kind: 'poll' }
	| { kind: 'redacted' }
	| { kind: 'unableToDecrypt' }
	| { kind: 'unknown' }
);

// Manually typed
export type StickerEventContent = {
	body: string;
	info: ImageInfo;
} & PlainMediaSource;
