// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { FormattedBody } from './FormattedBody.js';

/**
 * The payload for a notice message.
 */
export type NoticeMessageEventContent = {
	/**
	 * The notice text.
	 */
	body: string;
} & Partial<FormattedBody>;
