// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload for a notice message.
 */
export type NoticeMessageEventContent = {
	/**
	 * The notice text.
	 */
	body: string;
};
