// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OGTagsModel = {
	title: string | null;
	description: string | null;
	image: string | null;
	ogType: string | null;
	siteName: string | null;
	articleAuthor: string | null;
	articlePublishedTime: string | null;
	articleSection: string | null;
};
