// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { EncryptedFile } from './EncryptedFile.js';

/**
 * Metadata and [`PreviewImageSource`] of an [`UrlPreview`] image.
 *
 * Modelled after [OpenGraph Image Properties](https://ogp.me/#structured).
 */
export type PreviewImage = {
	/**
	 * The size of the image in bytes.
	 */
	'matrix:image:size': number | undefined;
	/**
	 * The width of the image in pixels.
	 */
	'og:image:width': number | undefined;
	/**
	 * The height of the image in pixels.
	 */
	'og:image:height': number | undefined;
	/**
	 * The mime_type of the image.
	 */
	'og:image:type': string | null;
} & ({ 'og:image': string } | { 'beeper:image:encryption': EncryptedFile });
