// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilliSecondsSinceUnixEpoch } from './MilliSecondsSinceUnixEpoch.js';

/**
 * Information about a single reaction stored in [`ReactionsByKeyBySender`].
 */
export type ReactionInfo = {
	timestamp: MilliSecondsSinceUnixEpoch;
	/**
	 * Current status of this reaction.
	 */
	status: 'localToLocal' | 'localToRemote' | 'remoteToRemote';
};
