// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactionInfo } from './ReactionInfo.js';

/**
 * Reactions grouped by key first, then by sender.
 *
 * This representation makes sure that a given sender has sent at most one
 * reaction for an event.
 */
export type ReactionsByKeyBySender = Record<string, Record<string, ReactionInfo>>;
