// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The content of a [replacement] relation.
 *
 * [replacement]: https://spec.matrix.org/latest/client-server-api/#event-replacements
 */
export type Replacement<C> = {
	/**
	 * The ID of the event being replaced.
	 */
	event_id: string;
	/**
	 * New content.
	 */
	new_content: C;
};
