// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A summary of the conditions for joining a restricted room.
 */
export type RestrictedSummary = {
	/**
	 * The room IDs which are specified by the join rules.
	 */
	allowed_room_ids: Array<string>;
};
