// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomModel = {
	id: string;
	/**
	 * Corresponds to `RoomDisplayName.to_string()`.
	 */
	displayName: string;
	avatarUrl: string | null;
	dmUserId: string | null;
};
