// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomsCollectionStatus =
	| { status: 'notLoaded'; message: string }
	| { status: 'loading'; message: string }
	| { status: 'loaded'; message: string }
	| { status: 'error'; message: string };
