// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a member considered to be a room hero.
 */
export type RoomHero = {
	/**
	 * The user id of the hero.
	 */
	user_id: string;
	/**
	 * The display name of the hero.
	 */
	display_name: string | null;
	/**
	 * The avatar url of the hero.
	 */
	avatar_url: string | null;
};
