// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendRoomMember } from './FrontendRoomMember.js';
import type { TimelineUiState } from './TimelineUiState.js';

/**
 * A serializable struct representing the state of a given Matrix Room.
 * Fields are not exposed to the adapter directly, the adapter can only serialize this struct.
 */
export type RoomScreen = {
	/**
	 * The room ID of the currently-shown room.
	 */
	roomId: string;
	/**
	 * The display name of the currently-shown room.
	 */
	roomName: string;
	/**
	 * The persistent UI-relevant states for the room that this widget is currently displaying.
	 */
	tlState: TimelineUiState | null;
	/**
	 * Known members of this room
	 */
	members: Record<string, FrontendRoomMember>;
	/**
	 * The users of this room that are currently typing a message
	 */
	typingUsers: Array<string>;
	/**
	 * Wether this room is still loading or not
	 */
	doneLoading: boolean;
};
