// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitedRoomInfo } from './InvitedRoomInfo.js';
import type { JoinedRoomInfo } from './JoinedRoomInfo.js';
import type { RoomsCollectionStatus } from './RoomsCollectionStatus.js';

/**
 * The struct containing all the data related to the homepage rooms list.
 * Fields are not exposed to the adapter directly, the adapter can only serialize this struct.
 */
export type RoomsList = {
	/**
	 * The list of all rooms that the user has been invited to.
	 */
	invitedRooms: Record<string, InvitedRoomInfo>;
	/**
	 * The set of all joined rooms and their cached preview info.
	 */
	allJoinedRooms: Record<string, JoinedRoomInfo>;
	/**
	 * The latest keywords entered into the `RoomFilterInputBar`.
	 *
	 * If empty, there are no filter keywords in use, and all rooms/spaces should be shown.
	 */
	filterKeywords: string;
	/**
	 * The list of invited rooms currently displayed in the UI, in order from top to bottom.
	 * This is a strict subset of the rooms present in `all_invited_rooms`, and should be determined
	 * by applying the `display_filter` to the set of `all_invited_rooms`.
	 */
	displayedInvitedRooms: Array<string>;
	/**
	 * The list of direct rooms currently displayed in the UI, in order from top to bottom.
	 * This is a strict subset of the rooms present in `all_joined_rooms`,
	 * and should be determined by applying the `display_filter && is_direct`
	 * to the set of `all_joined_rooms`.
	 */
	displayedDirectRooms: Array<string>;
	/**
	 * The list of regular (non-direct) joined rooms currently displayed in the UI,
	 * in order from top to bottom.
	 * This is a strict subset of the rooms in `all_joined_rooms`,
	 * and should be determined by applying the `display_filter && !is_direct`
	 * to the set of `all_joined_rooms`.
	 *
	 * **Direct rooms are excluded** from this; they are in `displayed_direct_rooms`.
	 */
	displayedRegularRooms: Array<string>;
	/**
	 * The latest status message that should be displayed in the bottom status label.
	 */
	status: RoomsCollectionStatus;
	/**
	 * The ID of the currently-selected room.
	 */
	currentActiveRoom: string | null;
	/**
	 * The maximum number of rooms that will ever be loaded.
	 */
	maxKnownRooms: number | null;
};
