// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The name of the room, either from the metadata or calculated
 * according to [matrix specification](https://matrix.org/docs/spec/client_server/latest#calculating-the-display-name-for-a-room)
 */
export type RoomDisplayName =
	| { kind: 'named'; name: string }
	| { kind: 'aliased'; name: string }
	| { kind: 'calculated'; name: string }
	| { kind: 'empty_was'; name: string }
	| { kind: 'empty' };
