// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMessageEventContent } from './AudioMessageEventContent.js';
import type { EmoteMessageEventContent } from './EmoteMessageEventContent.js';
import type { FileMessageEventContent } from './FileMessageEventContent.js';
import type { ImageMessageEventContent } from './ImageMessageEventContent.js';
import type { Mentions } from './Mentions.js';
import type { Relation } from './Relation.js';
import type { RoomMessageEventContentWithoutRelation } from './RoomMessageEventContentWithoutRelation.js';
import type { TextMessageEventContent } from './TextMessageEventContent.js';
import type { VideoMessageEventContent } from './VideoMessageEventContent.js';

/**
 * The content of an `m.room.message` event.
 *
 * This event is used when sending messages in a room.
 *
 * Messages are not limited to be text.
 */
export type RoomMessageEventContent = {
	/**
	 * The [mentions] of this event.
	 *
	 * This should always be set to avoid triggering the legacy mention push rules. It is
	 * recommended to modify this field only before calling a method that adds a relation. For
	 * example, [`make_replacement()`](Self::make_replacement) needs to know all the mentions
	 * beforehand to avoid re-triggering notifications for users that were already mentioned in
	 * the original event.
	 *
	 * [mentions]: https://spec.matrix.org/latest/client-server-api/#user-and-room-mentions
	 */
	'm.mentions'?: Mentions | null;
	'm.relates_to'?: Relation<RoomMessageEventContentWithoutRelation>;
} & (
	| ({ msgtype: 'm.audio' } & AudioMessageEventContent)
	| ({ msgtype: 'm.emote' } & EmoteMessageEventContent)
	| ({ msgtype: 'm.file' } & FileMessageEventContent)
	| ({ msgtype: 'm.image' } & ImageMessageEventContent)
	| ({ msgtype: 'm.text' } & TextMessageEventContent)
	| ({ msgtype: 'm.video' } & VideoMessageEventContent)
);
