// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMessageEventContent } from './AudioMessageEventContent.js';
import type { EmoteMessageEventContent } from './EmoteMessageEventContent.js';
import type { FileMessageEventContent } from './FileMessageEventContent.js';
import type { ImageMessageEventContent } from './ImageMessageEventContent.js';
import type { Mentions } from './Mentions.js';
import type { TextMessageEventContent } from './TextMessageEventContent.js';
import type { VideoMessageEventContent } from './VideoMessageEventContent.js';

/**
 * Form of [`RoomMessageEventContent`] without relation.
 */
export type RoomMessageEventContentWithoutRelation = {
	/**
	 * The [mentions] of this event.
	 *
	 * [mentions]: https://spec.matrix.org/latest/client-server-api/#user-and-room-mentions
	 */
	'm.mentions': Mentions | null;
} & (
	| ({ msgtype: 'm.audio' } & AudioMessageEventContent)
	| ({ msgtype: 'm.emote' } & EmoteMessageEventContent)
	| ({ msgtype: 'm.file' } & FileMessageEventContent)
	| ({ msgtype: 'm.image' } & ImageMessageEventContent)
	| ({ msgtype: 'm.text' } & TextMessageEventContent)
	| ({ msgtype: 'm.video' } & VideoMessageEventContent)
);
