// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendRoomMember } from './FrontendRoomMember.js';
import type { TimelineKind } from './TimelineKind.js';
import type { TimelineUiState } from './TimelineUiState.js';

/**
 * A serializable struct representing the state of a given Matrix Room.
 * Fields are not exposed to the adapter directly, the adapter can only serialize this struct.
 */
export type RoomScreen = {
	/**
	 * The timeline currently displayed by this RoomScreen, if any.
	 */
	timelineKind: TimelineKind | null;
	/**
	 * The display name of the currently-shown room.
	 */
	roomName: string;
	/**
	 * The persistent UI-relevant states for the room that this widget is currently displaying.
	 */
	tlState: TimelineUiState | null;
	/**
	 * Known members of this room
	 */
	members: Record<string, FrontendRoomMember>;
	/**
	 * The set of pinned events in this room.
	 */
	pinnedEvents: Array<string>;
	/**
	 * Whether this room has been successfully loaded (received from the homeserver).
	 */
	isLoaded: boolean;
	/**
	 * Whether or not all rooms have been loaded (received from the homeserver).
	 */
	allRoomsLoaded: boolean;
};
