// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JoinRuleSummary } from './JoinRuleSummary.js';
import type { RoomHero } from './RoomHero.js';
import type { RoomState } from './RoomState.js';

/**
 * The preview of a room, be it invited/joined/left, or not.
 */
export type RoomPreview = {
	/**
	 * The actual room id for this room.
	 *
	 * Remember the room preview can be fetched from a room alias id, so we
	 * might not know ahead of time what the room id is.
	 */
	room_id: string;
	/**
	 * The canonical alias for the room.
	 */
	canonical_alias: string | null;
	/**
	 * The room's name, if set.
	 */
	name: string | null;
	/**
	 * The room's topic, if set.
	 */
	topic: string | null;
	/**
	 * The MXC URI to the room's avatar, if set.
	 */
	avatar_url: string | null;
	/**
	 * The number of joined members.
	 */
	num_joined_members: bigint;
	/**
	 * The number of active members, if known (joined + invited).
	 */
	num_active_members: bigint | null;
	/**
	 * The room type (space, custom) or nothing, if it's a regular room.
	 */
	room_type: 'm.space' | null;
	/**
	 * What's the join rule for this room?
	 */
	join_rule: JoinRuleSummary | null;
	/**
	 * Is the room world-readable (i.e. is its history_visibility set to
	 * world_readable)?
	 */
	is_world_readable: boolean | null;
	/**
	 * Has the current user been invited/joined/left this room?
	 *
	 * Set to `None` if the room is unknown to the user.
	 */
	state: RoomState | null;
	/**
	 * The `m.room.direct` state of the room, if known.
	 */
	is_direct: boolean | null;
	/**
	 * Room heroes.
	 */
	heroes: Array<RoomHero> | null;
};
