// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum keeping track in which state the room is, e.g. if our own user is
 * joined, RoomState::Invited, or has left the room.
 */
export type RoomState = 'Joined' | 'Left' | 'Invited' | 'Knocked' | 'Banned';
