// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageEventContent } from './RoomMessageEventContent.js';

export type SendMessagePayload = {
	roomId: string;
	message: RoomMessageEventContent;
	replyToId: string | null;
	/**
	 * If set, the timeline used to send this message will be thread-focused
	 * on the given event id.
	 */
	threadRootId: string | null;
};
