// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageEventContent } from './RoomMessageEventContent.js';

export type SendMessagePayload = {
	roomId: string;
	threadRootEventId: string | null;
	message: RoomMessageEventContent;
	replyToId: string | null;
};
