// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload for a server notice message.
 */
export type ServerNoticeMessageEventContent = {
	/**
	 * A human-readable description of the notice.
	 */
	body: string;
	/**
	 * The type of notice being represented.
	 */
	server_notice_type: 'UsageLimitReached';
	/**
	 * A URI giving a contact method for the server administrator.
	 *
	 * Required if the notice type is `m.server_notice.usage_limit_reached`.
	 */
	admin_contact: string | null;
	/**
	 * The kind of usage limit the server has exceeded.
	 *
	 * Required if the notice type is `m.server_notice.usage_limit_reached`.
	 */
	limit_type: 'MonthlyActiveUser' | null;
};
