// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a tag.
 */
export type TagInfo = {
	/**
	 * Value to use for lexicographically ordering rooms with this tag.
	 *
	 * If you activate the `compat-tag-info` feature, this field can be decoded as a stringified
	 * floating-point value, instead of a number as it should be according to the specification.
	 */
	order?: number | null;
};
