// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload for a text message.
 */
export type TextMessageEventContent = {
	/**
	 * The body of the message.
	 */
	body: string;
};
