// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The mapped thread summary containing the latest item in this thread + additionnal infos.
 */
export type ThreadSummary = {
	eventFormattedSummary: string;
	senderId: string;
	numReplies: number;
	privateReadReceiptEventId: string | null;
	publicReadReceiptEventId: string | null;
};
