// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InReplyTo } from './InReplyTo.js';

/**
 * The content of a [thread] relation.
 *
 * [thread]: https://spec.matrix.org/latest/client-server-api/#threading
 */
export type Thread = {
	rel_type: 'm.thread';
	/**
	 * The ID of the root message in the thread.
	 */
	event_id: string;
	/**
	 * A reply relation.
	 *
	 * If this event is a reply and belongs to a thread, this points to the message that is being
	 * replied to, and `is_falling_back` must be set to `false`.
	 *
	 * If this event is not a reply, this is used as a fallback mechanism for clients that do not
	 * support threads. This should point to the latest message-like event in the thread and
	 * `is_falling_back` must be set to `true`.
	 */
	'm.in_reply_to': InReplyTo | null;
	/**
	 * Whether the `m.in_reply_to` field is a fallback for older clients or a genuine reply in a
	 * thread.
	 */
	is_falling_back?: boolean;
};
