// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a thumbnail.
 */
export type ThumbnailInfo = {
	/**
	 * The height of the thumbnail in pixels.
	 */
	h: number | null;
	/**
	 * The width of the thumbnail in pixels.
	 */
	w: number | null;
	/**
	 * The MIME type of the thumbnail, e.g. "image/png."
	 */
	mimetype: string | null;
	/**
	 * The file size of the thumbnail in bytes.
	 */
	size: number | null;
};
