// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Thumbnail = {
	/**
	 * The raw bytes of the thumbnail.
	 */
	data: ArrayBuffer;
	/**
	 * The type of the thumbnail, this will be used as the content-type header.
	 */
	contentType: string;
	/**
	 * The height of the thumbnail in pixels.
	 */
	height: number;
	/**
	 * The width of the thumbnail in pixels.
	 */
	width: number;
	/**
	 * The file size of the thumbnail in bytes.
	 */
	size: number;
};
