// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { TimelineItem } from './TimelineItem.js';

/**
 * The UI-side state of a single room's timeline, which is only accessed/updated by the UI thread.
 *
 * This struct should only include states that need to be persisted for a given room
 * across multiple `Hide`/`Show` cycles of that room's timeline within a RoomScreen.
 * If a state is more temporary and shouldn't be persisted when the timeline is hidden,
 * then it should be stored in the RoomScreen widget itself, not in this struct.
 */
export type TimelineUiState = {
	/**
	 * The ID of the room that this timeline is for.
	 */
	roomId: string;
	/**
	 * The power levels of the currently logged-in user in this room.
	 */
	userPower: (
		| 'ban'
		| 'invite'
		| 'kick'
		| 'redact'
		| 'notifyRoom'
		| 'location'
		| 'message'
		| 'reaction'
		| 'roomMessage'
		| 'roomRedaction'
		| 'sticker'
		| 'roomAvatar'
		| 'roomName'
		| 'roomPinnedEvents'
		| 'roomTopic'
	)[];
	/**
	 * Whether this room's timeline has been fully paginated, which means
	 * that the oldest (first) event in the timeline is locally synced and available.
	 * When `true`, further backwards pagination requests will not be sent.
	 *
	 * This must be reset to `false` whenever the timeline is fully cleared.
	 */
	fullyPaginated: boolean;
	/**
	 * The list of items (events) in this room's timeline that our client currently knows about.
	 */
	items: TimelineItem[];
	/**
	 * Whether the user has scrolled past their latest read marker.
	 *
	 * This is used to determine whether we should send a fully-read receipt
	 * after the user scrolls past their "read marker", i.e., their latest fully-read receipt.
	 * Its value is determined by comparing the fully-read event's timestamp with the
	 * first and last timestamp of displayed events in the timeline.
	 * When scrolling down, if the value is true, we send a fully-read receipt
	 * for the last visible event in the timeline.
	 *
	 * When new message come in, this value is reset to `false`.
	 */
	scrolledPastReadMarker: boolean;
	latestOwnUserReceipt: { ts: number };
};
