// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MsgLikeContent } from './MsgLikeContent.js';
import type { VirtualTimelineItem } from './VirtualTimelineItem.js';

/**
 * Corresponds to the FrontendTimelineItem struct.
 * Renamed for readability
 */
export type TimelineItem = {
	uniqueId: string;
	eventId: string | null;
	timelineItemId: string;
	timestamp: number | null;
	isOwn: boolean;
	isLocal: boolean;
	abilities: MessageAbility[];
} & (
	| { kind: 'msgLike'; data: MsgLikeContent }
	| { kind: 'virtual'; data: VirtualTimelineItem }
	| { kind: 'stateChange'; data: StateEvent }
	| { kind: 'error'; data: TimelineErrorItem }
	| { kind: 'call' }
);

// Manually typed
export type StateEvent =
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	| { kind: 'otherState'; body: any }
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	| { kind: 'membershipChange'; body: any }
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	| { kind: 'profileChange'; body: any };

// Manually typed
export type MessageAbility =
	| 'canReact'
	| 'canReplyTo'
	| 'canEdit'
	| 'canPin'
	| 'canUnpin'
	| 'canDelete'
	| 'hasHtml';

/**
 * Renamed from "FrontendTimelineErrorItem"
 */
export type TimelineErrorItem = { error: string };
