// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineKind =
	| { kind: 'mainRoom'; roomId: string }
	| { kind: 'thread'; roomId: string; threadRootEventId: string };
