// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extensible event fallback data for voice messages, from the
 * [first version of MSC3245][msc].
 *
 * [msc]: https://github.com/matrix-org/matrix-spec-proposals/blob/83f6c5b469c1d78f714e335dcaa25354b255ffa5/proposals/3245-voice-messages.md
 */
export type UnstableVoiceContentBlock = Record<string, never>;
