// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnstableAmplitude } from './UnstableAmplitude.js';

/**
 * Extensible event fallback data for audio messages, from the
 * [first version of MSC3245][msc].
 *
 * [msc]: https://github.com/matrix-org/matrix-spec-proposals/blob/83f6c5b469c1d78f714e335dcaa25354b255ffa5/proposals/3245-voice-messages.md
 */
export type UnstableAudioDetailsContentBlock = {
	/**
	 * The duration of the audio in milliseconds.
	 *
	 * Note that the MSC says this should be in seconds but for compatibility with the Element
	 * clients, this uses milliseconds.
	 */
	duration: number;
	/**
	 * The waveform representation of the audio content, if any.
	 *
	 * This is optional and defaults to an empty array.
	 */
	waveform?: Array<UnstableAmplitude>;
};
