// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unstable version of the amplitude of a waveform sample.
 *
 * Must be an integer between 0 and 1024.
 */
export type UnstableAmplitude = number;
