// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { PreviewImage } from './PreviewImage.js';

// PARTLY MANUALLY TYPED.
// The original Rust struct contains "flatten", that isn't supported
// by ts-rs

/**
 * Preview Information for a URL matched in the message's text, according to
 * [MSC 4095](https://github.com/matrix-org/matrix-spec-proposals/pull/4095).
 */
export type UrlPreview = {
	/**
	 * The url this was matching on.
	 */
	matched_url: string | null;
	/**
	 * Canonical URL according to open graph data.
	 */
	'og:url': string | null;
	/**
	 * Title to use for the preview.
	 */
	'og:title': string | null;
	/**
	 * Description to use for the preview.
	 */
	'og:description': string | null;
} & PreviewImage;
