// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information retrieved about a user: their displayable name, ID, and known avatar state.
 */
export type UserProfile = {
	user_id: string;
	/**
	 * The user's default display name, if set.
	 * Note that a user may have per-room display names,
	 * so this should be considered a fallback.
	 */
	username: string | null;
	avatar_url: string | null;
};
