// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedFile } from './EncryptedFile.js';
import type { VideoInfo } from './VideoInfo.js';

/**
 * The payload for a video message.
 */
export type VideoMessageEventContent = {
	/**
	 * A description of the video.
	 *
	 * If the `filename` field is not set or has the same value, this is the filename of the
	 * uploaded file. Otherwise, this should be interpreted as a user-written media caption.
	 */
	body: string;
	/**
	 * The original filename of the uploaded file as deserialized from the event.
	 *
	 * It is recommended to use the `filename` method to get the filename which automatically
	 * falls back to the `body` field when the `filename` field is not set.
	 */
	filename: string | null;
	/**
	 * Metadata about the video clip referred to in `source`.
	 */
	info: VideoInfo | null;
} & ({ url: string } | { file: EncryptedFile });
