// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThumbnailMediaSource } from '../matrix-requests/media.js';
import type { ThumbnailInfo } from './ThumbnailInfo.js';

/**
 * Metadata about a video.
 */
export type VideoInfo = {
	/**
	 * The duration of the video in milliseconds.
	 */
	duration?: number | null;
	/**
	 * The height of the video in pixels.
	 */
	h: number | null;
	/**
	 * The width of the video in pixels.
	 */
	w: number | null;
	/**
	 * The mimetype of the video, e.g. "video/mp4".
	 */
	mimetype: string | null;
	/**
	 * The size of the video in bytes.
	 */
	size: number | null;
	/**
	 * Metadata about the image referred to in `thumbnail_source`.
	 */
	thumbnail_info: ThumbnailInfo | null;
	/**
	 * The [BlurHash](https://blurha.sh) for this video.
	 *
	 * This uses the unstable prefix in
	 * [MSC2448](https://github.com/matrix-org/matrix-spec-proposals/pull/2448).
	 */
	'xyz.amorgan.blurhash': string | null;
	/**
	 * The [ThumbHash](https://evanw.github.io/thumbhash/) for this video.
	 *
	 * This uses the unstable prefix in
	 * [MSC2448](https://github.com/matrix-org/matrix-spec-proposals/pull/2448).
	 */
	'xyz.amorgan.thumbhash': string | null;
} & ThumbnailMediaSource;
